# Generated by Django 6.1 on 2026-10-02 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_manage_blog_posts", "Может управлять публикациями в блоге")],
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="view_count",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(help_text="Введите содержание публикации", verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Если отмечено — публикация видна всем", verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(help_text="Введите заголовок публикации", max_length=200, verbose_name="Заголовок"),
        ),
    ]
